export enum QuestionCategory {
  OPENER = 'OPENER',
  CONFLICT = 'CONFLICT',
  FAILURE = 'FAILURE',
  LEADERSHIP = 'LEADERSHIP',
  TEAMWORK = 'TEAMWORK',
  INITIATIVE = 'INITIATIVE',
  PROBLEM_SOLVING = 'PROBLEM_SOLVING',
  MOTIVATION = 'MOTIVATION',
  LOGISTICS = 'LOGISTICS',
}
